---
title: Curriculum Vitae `r format(Sys.Date(), "%Y")`
params:
  language: spanish
  profile: academic

output:
  html_document:
    theme: spacelab
    highlight: espresso
    number_sections: true
    css: css/style.css
    includes:
      in_header: header.html
---

```{r setup, include=FALSE}
library(yaml)
config <- yaml::read_yaml("shared_params.yml")
#  use private : false in shared_params.yml for your public profile                # IMPORTANT!
params_private <- config$private
params_location <- config$location
params_allow_proof_documents <- config$proof
params_valid_languages <- config$valid_languages
params_valid_profiles <- config$valid_profiles

knitr::opts_chunk$set(echo = TRUE)
```

``` {r echo=F}
params_language <- params$language
params_profile <- params$profile
if (!params_profile %in% params_valid_profiles) {
  params_profile <- "general"
}

field_names_file <- "names/fields.yml"
field_names <- yaml.load_file(field_names_file)

chapter_filename <- "names/chapters.yml"
chapters_names <- yaml.load_file(chapter_filename)
```

```{r, echo=FALSE, results='asis'}
cat(
  knitr::knit_child("Rmd/main.Rmd", quiet = TRUE)
)
```
