---
title: "main"
---
``` {r, echo=F, message = FALSE, eval=TRUE}
require(yaml)
require(purrr)

chapter_filename <- "names/chapters.yml"
chapters_names <- yaml.load_file(chapter_filename)

field_names_file <- "names/fields.yml"
field_names <- yaml.load_file(field_names_file)
```


<!-- MAIN CHAPTERS IN THREE LANGUAGES-->

``` {r, echo=F}
# language<-"english"
SectionIts <- read.table(
  text =
    "dataType english spanish portuguese
1 personItem \"Personal Data\" \"Datos personales\" \"Dados pessoais\"
2 summaryItem Summary Resumen Resumo
3 linkItem \"Personal links\" \"Links personales\" \"Links pessoais\"
4 repoItem \"Software: packages, scripts, pages\" \"Software: bibliotecas, scripts, páginas\" \"Software: pacotes, scripts, páginas\"
5 posiItem \"Professional experience\"  \"Experiencia profesional\"  \"Experiência profisional\"
6 studyItem \"Main Degrees\" \"Títulos\" \"Títulos\"
7 articleItem Articles \"Artículos científicos\" \"Artigos científicos\"
8 talkItem \"Talks in Events\" \"Conferencias en Eventos\" \"Palestras em eventos\"
9 abstractItem \"Congress presentations and abstracts\" \"Presentaciones y resumenes en eventos\" \"Apresentações e resumos em encontros\"
10 languageItem \"Language proficiency\" \"Dominio de idiomas\" \"Proficiência em línguas\"
11 mentoringItem Mentoring \"Supervisión de investigadores\" \"Orientação de pesquisa\"
12 courseItem \"Courses taught\" \"Cursos impartidos\" \"Cursos ministrados\"
13 lectureItem Lectures \"Asignaturas ofrecidas\" \"Disciplinas ministradas\"
14 learningItem \"Taken Courses and Workshops\" \"Cursos y talleres tomados\" \"Cursos e oficinas tomados\"
15 armyItem \"Military service\" \"Servicio militar\" \"Serviço militar\"
16 perrefItem \"Personal references\" \"Referencias personales\" \"Referências pessoais\"
17 donateItem Donate Donación Doação
", header = T, stringsAsFactors = F
)

languagePos <- which(colnames(SectionIts) == language)
```

<!-- MAIN FIELDS IN THREE LANGUAGES-->

``` {r, echo=F, results="hide"}

fieldIts <- read.table(
  text =
    "             field             english                    spanish            portuguese
      summary1               Part1
      summary2               Part2
      summary3               Part3
      summary4               Part4
      summary6               Part6
       activity       \"Main activity\"        \"Actividad principal\"   \"Atividade principal\"
        address             Address                  Dirección              Endereço
          author              author
          begin               Begin                     Inicio                Início
      birthCity                  in                         en                    em
      birthdate \"Place and birthdate\"      \"Lugar y fecha de nac.\" \"Local e data de nasc.\"
           book
        classif
        contact       \"Inst. contact\" \"Contacto de la institución\" \"Contato da institução\"
     curriculum          Curriculum
       cvlattes           CV-Lattes
           date
    diplomadate        \"Diploma date\"           \"Fecha de diploma\"       \"Data do diploma\"
   distinctions        Distinctions               Distinciones            Distinções
          email              E-mail
       emphasis            Emphasis    \"Linea de profundización\"     \"Linha de pesquisa\"
            end                 End                        Fin                   Fim
          event               event
         gitlab              Gitlab
         github              Github
          grade       \"Grade average\"          \"Promedio de notas\"        \"Media de notas\"
             id                  Id                     Cédula                    Id
    idIssueDate                  in                         el                     o
   idIssuePlace           \"issued in\"                \"expedida en\"            \"emitida em\"
    institution         Institution                Institución            Institução
        journal
       keywords            Keywords             Palabras-clave        Palavras-chave
       language
          level               Level                      Nivel                 Nivel
           url               link
           mode
           name                Name                     Nombre                  Nome
      oprojects      \"Other projects\"            \"Otros proyectos\"       \"Outros projetos\"
         orilan   \"language\"            \"idioma\"       \"idioma\"
      orcid               ORCID
      oripoints
           pages
          period              Period                    Periodo               Periodo
          phonewa        \"Phone (w.a.)\"            \"Teléfono (w.a.)\"       \"Telefone (w.a.)\"
          phone        \"Phone\"                   \"Teléfono\"                  \"Telefone\"
          place
     profIdDate           \"issued in\"               \"expedida el\"            \"emitida no\"
         profId       \"Professional Id\"        \"Tarjeta profesional\"              \"Prof. Id\"
       projects            Projects                  Proyectos              Projetos
          proof
       position            Position                    Cargo                  Ocupação
    publication         Publication                Publicación            Publicação
           repo               Repo.
   researchgate        ResearchGate
    scholarship         Scholarship                       Beca                 Bolsa
      signature              Signed                    Firmado              Assinado
          skype               Skype
        student             Student                 Estudiante             Estudante
     supervisor          Supervisor                   Director            Orientador
           term                Term                   Duración               Duração
         thesis              Thesis                      Tesis                  Tese
          title               Title                     Título                Título
           field
 validationdate     \"Validation date\"     \"Fecha de convalidación\"   \"Data de revalidação\"
            volume
        webpage            Web-page                 Página-web            Página-web
        webpage2           Web-page                 Página-web            Página-web
        webapp             Web-app                  Web-app               Web-app
        workplace     \"Workplace\"               \"Entidad\"           \"Afiliação\"
            year
", fill = T, header = T, stringsAsFactors = F
)
fieldIts[fieldIts == ""] <- NA
fieldIts <- data.frame(t(apply(fieldIts, 1, zoo::na.locf)), stringsAsFactors = F)
fieldIts[fieldIts == "-"] <- NA
```

<!-- FUNCTIONS -->

``` {r, echo = FALSE, message = FALSE}
R_path <- normalizePath(file.path(getwd(), "R"))
source(file.path(R_path, "functions.R"))
source(file.path(R_path, "list_to_rmarkdown.R"))
source(file.path(R_path, "process_yaml.R"))
source(file.path(R_path, "bib.R"))
```

<!-- CHUNK CONFIG -->

```{r, include=FALSE}
knitr::opts_chunk$set(comment = NA)
knitr::opts_chunk$set(dev = c("png")) # important distorted zero in last figure
# knitr::opts_chunk$set(out.extra = 'style="float:right;"')
# knitr::opts_chunk$set(out.width = "75%",
```

<!-- ########################################### -->
<!-- # -->
<!-- #     read .R files -->
<!-- # -->
<!-- ########################################### -->

```{r, include=FALSE}
mypath <- normalizePath(getwd())
tryCatch(lapply(list.files(pattern = "major", path = paste0(mypath, "/major")), function(x) {
  # mypath<-normalizePath(getwd())
  source(paste0(mypath, "/major/", x))
}), error = function(e) {
  cat("not found")
})

############################################
#
#     Use the word (string) data in every element of your major...R files
#
###########################################

listofAllIts <- ls(pattern = "data")
listofAllItsr <- lapply(listofAllIts, function(x) eval(parse(text = x)))
```

<!-- PERSONAL DATA -->

``` {r, echo=F, results="asis", eval = T}
chapter <- "personal"

yaml_file <- file.path("data", paste0(chapter, ".yml"))

data_list_from_yaml <- read_yml_and_check_levels(yaml_file)

config_links <- yaml::read_yaml(file.path("config", paste0(chapter, ".yml")))
chapter_content <- ""

if (attr(data_list_from_yaml, "yaml_type") == "one_level") {
  chapter_content <- map(config_links, \(x) render_from_list(x, list_from_yaml = data_list_from_yaml)) |> invisible()
} else if (attr(data_list_from_yaml, "yaml_type") == "multi_level") {
  chapter_content <- map(data_list_from_yaml, \(y) {
    map(config_links, \(x) render_from_list(x, list_from_yaml = y)) |> invisible()
  }) |>
    invisible()
}
chapter_content_concat <- chapter_content |>
  unlist() |>
  paste0(collapse = "")

if (chapter_content_concat != "") {
  section_title <- get_chapter_title(data_list_from_yaml, chapter)
  cat(paste0("<br>   \n  \n# ", section_title))
  cat(chapter_content_concat)
}
```


<!-- Chronology summary -->

``` {r, results="asis", echo=F}
chapter <- "chronology"

yaml_file <- file.path("data", paste0(chapter, ".yml"))

data_list_from_yaml <- read_yml_and_check_levels(yaml_file)

config_links <- yaml::read_yaml(file.path("config", paste0(chapter, ".yml")))
chapter_content <- ""

if (attr(data_list_from_yaml, "yaml_type") == "one_level") {
  chapter_content <- map(config_links, \(x) render_from_list(x, list_from_yaml = data_list_from_yaml)) |> invisible()
} else if (attr(data_list_from_yaml, "yaml_type") == "multi_level") {
  chapter_content <- map(data_list_from_yaml, \(y) {
    map(config_links, \(x) render_from_list(x, list_from_yaml = y)) |> invisible()
  }) |>
    invisible()
}
chapter_content_concat <- chapter_content |>
  unlist() |>
  paste0(collapse = "")

if (chapter_content_concat != "") {
  section_title <- get_chapter_title(data_list_from_yaml, chapter)
  cat(paste0("<br>   \n  \n# ", section_title))
  cat(chapter_content_concat)
}
```

<!-- SUMMARY -->

``` {r, results="asis", echo=F}
chapter <- "summary"

yaml_file <- file.path("data", paste0(chapter, ".yml"))

data_list_from_yaml <- read_yml_and_check_levels(yaml_file)

config_links <- yaml::read_yaml(file.path("config", paste0(chapter, ".yml")))
chapter_content <- ""

if (attr(data_list_from_yaml, "yaml_type") == "one_level") {
  chapter_content <- map(config_links, \(x) render_from_list(x, list_from_yaml = data_list_from_yaml)) |> invisible()
} else if (attr(data_list_from_yaml, "yaml_type") == "multi_level") {
  chapter_content <- map(data_list_from_yaml, \(y) {
    map(config_links, \(x) render_from_list(x, list_from_yaml = y)) |> invisible()
  }) |>
    invisible()
}
chapter_content_concat <- chapter_content |>
  unlist() |>
  paste0(collapse = "")

if (chapter_content_concat != "") {
  section_title <- get_chapter_title(data_list_from_yaml, chapter)
  cat(paste0("<br>   \n  \n# ", section_title))
  cat(chapter_content_concat)
}
```


<!-- Personal Links: -->

``` {r, results="asis", echo=F, eval=T}
chapter <- "links"

yaml_file <- file.path("data", paste0(chapter, ".yml"))

data_list_from_yaml <- read_yml_and_check_levels(yaml_file)

config_links <- yaml::read_yaml(file.path("config", paste0(chapter, ".yml")))
chapter_content <- ""

if (attr(data_list_from_yaml, "yaml_type") == "one_level") {
  chapter_content <- map(config_links, \(x) render_from_list(x, list_from_yaml = data_list_from_yaml)) |> invisible()
} else if (attr(data_list_from_yaml, "yaml_type") == "multi_level") {
  chapter_content <- map(data_list_from_yaml, \(y) {
    map(config_links, \(x) render_from_list(x, list_from_yaml = y)) |> invisible()
  }) |>
    invisible()
}
chapter_content_concat <- chapter_content |>
  unlist() |>
  paste0(collapse = "")

if (chapter_content_concat != "") {
  section_title <- get_chapter_title(data_list_from_yaml, chapter)
  cat(paste0("<br>   \n  \n# ", section_title))
  cat(chapter_content_concat)
}
```

<!-- DEVELOPMENT PERIOD -->

``` {r, results="asis", echo=F, eval=T}
chapter <- "development"

yaml_file <- file.path("data", paste0(chapter, ".yml"))

data_list_from_yaml <- read_yml_and_check_levels(yaml_file)

config_links <- yaml::read_yaml(file.path("config", paste0(chapter, ".yml")))

chapter_content <- map(data_list_from_yaml, \(y) {
  map(config_links, \(x) render_from_list(x, list_from_yaml = y)) |> invisible()
}) |>
  invisible()

chapter_content_concat <- chapter_content |>
  unlist() |>
  paste0(collapse = "")

if (chapter_content_concat != "") {
  section_title <- get_chapter_title(data_list_from_yaml, chapter)
  cat(paste0("<br>   \n  \n# ", section_title))
  cat(chapter_content_concat)
}
```

<!-- WORK EXPERIENCE -->

``` {r, results="asis", echo=F, eval=T}
chapter <- "positions"

yaml_file <- file.path("data", paste0(chapter, ".yml"))

data_list_from_yaml <- read_yml_and_check_levels(yaml_file)

config_links <- yaml::read_yaml(file.path("config", paste0(chapter, ".yml")))

chapter_content <- map(data_list_from_yaml, \(y) {
  map(config_links, \(x) render_from_list(x, list_from_yaml = y)) |> invisible()
}) |>
  invisible()

chapter_content_concat <- chapter_content |>
  unlist() |>
  paste0(collapse = "")

if (chapter_content_concat != "") {
  section_title <- get_chapter_title(data_list_from_yaml, chapter)
  cat(paste0("<br>   \n  \n# ", section_title))
  cat(chapter_content_concat)
}
```


<!-- DEGREES -->

``` {r, results="asis", echo=F, eval=T}
chapter <- "university_degrees"

yaml_file <- file.path("data", paste0(chapter, ".yml"))

data_list_from_yaml <- read_yml_and_check_levels(yaml_file)

config_links <- yaml::read_yaml(file.path("config", paste0(chapter, ".yml")))

chapter_content <- map(data_list_from_yaml, \(y) {
  map(config_links, \(x) render_from_list(x, list_from_yaml = y)) |> invisible()
}) |>
  invisible()

chapter_content_concat <- chapter_content |>
  unlist() |>
  paste0(collapse = "")

if (chapter_content_concat != "") {
  section_title <- get_chapter_title(data_list_from_yaml, chapter)
  cat(paste0("<br>   \n  \n# ", section_title))
  cat(chapter_content_concat)
}
```

<!-- LANGUAGE PROFICIENCY -->

``` {r, results="asis", echo=F, eval=T}
chapter <- "languages"

yaml_file <- file.path("data", paste0(chapter, ".yml"))

data_list_from_yaml <- read_yml_and_check_levels(yaml_file)

config_links <- yaml::read_yaml(file.path("config", paste0(chapter, ".yml")))

chapter_content <- map(data_list_from_yaml, \(y) {
  map(config_links, \(x) render_from_list(x, list_from_yaml = y)) |> invisible()
}) |>
  invisible()

chapter_content_concat <- chapter_content |>
  unlist() |>
  paste0(collapse = "")

if (chapter_content_concat != "") {
  section_title <- get_chapter_title(data_list_from_yaml, chapter)
  cat(paste0("<br>   \n  \n# ", section_title))
  cat(chapter_content_concat)
}
```

<!-- articles -->

``` {r, results="asis", echo=F, eval=T}
chapter <- "publications"

yaml_file <- process_bib_folder()

data_list_from_yaml <- read_yml_and_check_levels(yaml_file)

config_links <- yaml::read_yaml(file.path("config", paste0(chapter, ".yml")))

chapter_content <- map(data_list_from_yaml, \(y) {
  map(config_links, \(x) render_from_list(x, list_from_yaml = y)) |> invisible()
}) |>
  invisible()

chapter_content_concat <- chapter_content |>
  unlist() |>
  paste0(collapse = "")

if (chapter_content_concat != "") {
  section_title <- get_chapter_title(data_list_from_yaml, chapter)
  cat(paste0("<br>   \n  \n# ", section_title))
  cat(chapter_content_concat)
}
```

<!-- software -->

``` {r, results="asis", echo=F, eval=T}
chapter <- "software"

yaml_file <- file.path("data", paste0(chapter, ".yml"))

data_list_from_yaml <- read_yml_and_check_levels(yaml_file)

config_links <- yaml::read_yaml(file.path("config", paste0(chapter, ".yml")))

chapter_content <- map(data_list_from_yaml, \(y) {
  map(config_links, \(x) render_from_list(x, list_from_yaml = y)) |> invisible()
}) |>
  invisible()

chapter_content_concat <- chapter_content |>
  unlist() |>
  paste0(collapse = "")

if (chapter_content_concat != "") {
  section_title <- get_chapter_title(data_list_from_yaml, chapter)
  cat(paste0("<br>   \n  \n# ", section_title))
  cat(chapter_content_concat)
}
```

<!-- COURSES GIVEN -->

``` {r, results="asis", echo=F, eval=T}
chapter <- "lectures"

yaml_file <- file.path("data", paste0(chapter, ".yml"))

data_list_from_yaml <- read_yml_and_check_levels(yaml_file)

config_links <- yaml::read_yaml(file.path("config", paste0(chapter, ".yml")))

chapter_content <- map(data_list_from_yaml, \(y) {
  map(config_links, \(x) render_from_list(x, list_from_yaml = y)) |> invisible()
}) |>
  invisible()

chapter_content_concat <- chapter_content |>
  unlist() |>
  paste0(collapse = "")

if (chapter_content_concat != "") {
  section_title <- get_chapter_title(data_list_from_yaml, chapter)
  cat(paste0("<br>   \n  \n# ", section_title))
  cat(chapter_content_concat)
}
```

<!-- RESEARCH SUPERVISOR - MENTORING-->

``` {r, results="asis", echo=F}
MentoringCasted <- readDataTypes("mentoringItem")

if (nrow(MentoringCasted) > 0) {
  for (i in 1:nrow(MentoringCasted)) {
    addFields("title", xCasted = MentoringCasted, xFielddata = fieldIts, spaces = 0, xtitle = F, separator = "", Bold = T, Section = T)
    addFields(c("student", "institution"), "period",
      xCasted = MentoringCasted, xFielddata = fieldIts,
      spaces = 0, xtitle = T, separator = "<br>", Bold = F, Section = F, xtitleRight = F
    )
  }
}
``` 

<!-- GIVEN COURSES -->

``` {r, results="asis", echo=F}
CoursesCasted <- readDataTypes("courseItem")

if (nrow(CoursesCasted) > 0) {
  for (i in 1:nrow(CoursesCasted)) {
    addFields("title", "term", xCasted = CoursesCasted, xFielddata = fieldIts, spaces = 0, xtitle = F, separator = "", Bold = T, Section = T, FontSizeRightSmall = T)
    addFields("event", "period", xCasted = CoursesCasted, xFielddata = fieldIts, spaces = 0, xtitle = F, separator = "", Bold = F, Section = F)
  }
}
``` 

<!-- talks -->

``` {r, results="asis", echo=F}
talkCasted <- readDataTypes("talkItem")

if (nrow(talkCasted) > 0) {
  for (i in 1:nrow(talkCasted)) {
    addFields("title", xCasted = talkCasted, xFielddata = fieldIts, xtitle = F, Section = T, separator = "")
    addFields(c("event", "orilan"), "date", talkCasted, fieldIts, xtitle = F, Section = F, separator = ". ")
    addFields("place", xCasted = talkCasted, xFielddata = fieldIts, xtitle = F, Section = F, separator = "")
  }
}
``` 


<!-- CONGRESS ABSTRACTS -->

``` {r, results="asis", echo=F}
abstractCasted <- readDataTypes("abstractItem")

if (nrow(abstractCasted) > 0) {
  for (i in 1:nrow(abstractCasted)) {
    addFields("title", "mode", abstractCasted, fieldIts, xtitle = F, Section = T, separator = ". ", FontSizeRightSmall = T)
    addFields("author", "date", xCasted = abstractCasted, xFielddata = fieldIts, spaces = 1, xtitle = F, separator = ". ")
    addFields(c("event", "place"), NA, abstractCasted, fieldIts, spaces = 1, xtitle = F, separator = ". ")
    addFields(c("book", "pages", "orilan"), NA, abstractCasted, fieldIts, spaces = 1, xtitle = F, separator = ". ")
  }
}
``` 



<!-- TAKEN COURSES -->

``` {r, results="asis", echo=F}
LearningCasted <- readDataTypes("learningItem")

if (nrow(LearningCasted) > 0) {
  for (i in 1:nrow(LearningCasted)) {
    addFields("title", "type",
      xCasted = LearningCasted, xFielddata = fieldIts,
      spaces = 0, xtitle = F, separator = "", Bold = F, Section = T, FontSizeRightSmall = T
    )
    addFields("institution", "term",
      xCasted = LearningCasted, xFielddata = fieldIts,
      spaces = 0, xtitle = F, separator = "", Bold = F, Section = F
    )
    addFields("orilan", "period",
      xCasted = LearningCasted, xFielddata = fieldIts,
      spaces = 0, xtitle = F, separator = "", Bold = F, Section = F
    )
  }
}
``` 

<!-- MILITARY -->

``` {r, results="asis", echo=F}
ArmyCasted <- readDataTypes("armyItem")

if (nrow(ArmyCasted) > 0) {
  for (i in 1:nrow(ArmyCasted)) {
    addFields("institution", "period",
      xCasted = ArmyCasted, xFielddata = fieldIts,
      spaces = 0, xtitle = F, separator = "", Bold = F, Section = F
    )
  }
}
```

<!-- personal references -->

``` {r, results="asis", echo=F}
PerRefCasted <- readDataTypes("perrefItem")
if (nrow(PerRefCasted) > 0) {
  for (i in 1:nrow(PerRefCasted)) {
    addFields("name", xCasted = PerRefCasted, xFielddata = fieldIts, spaces = 0, xtitle = F, separator = "", Bold = F, Section = T)
    addFields(c("position", "workplace", "phonewa", "email"),
      xCasted = PerRefCasted, xFielddata = fieldIts,
      spaces = 0, xtitle = T, separator = "<br>", Bold = F, Section = F
    )
  }
}
```

<!-- donate -->

``` {r, results="asis", echo=F}
DonCasted <- readDataTypes("donateItem")
if (nrow(DonCasted) > 0) {
  for (i in 1:nrow(DonCasted)) {
    addFields(c("url", "badges"),
      xCasted = DonCasted, xFielddata = fieldIts,
      spaces = 2, xtitle = F, separator = "", Bold = F, Section = F
    )
  }
}
``` 
