summarydata <- read.table(
  text =
    " field english spanish portuguese
summary1 \"  \nI have worked in genetics and plant and human cytogenetics. Having extensive wet experience in techniques such as estimation of genomic size by cytometry, sister chromatids exchange, G-banding, FISH, NGS read processing. I also have experience with molecular cytogenetic protocols such as DNA extraction, Nick translation, restriction reactions and PCR. Other techniques were applied in practical courses such as RNA extraction and microsatellites. \"  \"  \nTengo experiencia en genética y citogenética humana (IGH - PUJ), en técnicas como medición de tamaño genómico por citometría, intercambio de cromátides hermanas, bandas G, FISH. También tengo experiencia con protocolos de biología molecular como extracción de DNA, Nick translation, reacciones de restricción y PCR. Otras técnicas fueron aplicadas en cursos prácticos como extracción de RNA y microsatélites.\" \"  \nTenho experiência em genética e citogenética humana (IGH - PUJ) e vegetal, em técnicas como medição do tamanho genômico por citometria, troca de cromátides irmãs, bandas G, FISH. Também tenho experiência com protocolos citogenéticos moleculares, como extração de DNA, tradução de Nick, reações de restrição e PCR. Outras técnicas foram aplicadas em cursos práticos, como extração de RNA e microssatélites. \"
summary6 \"  \nI have worked as freelance (B2B) building Shiny Apps, including making reports (from SQL data)\"  \"  \nHe trabajado como freelance (B2B) haciendo Shiny Apps, que incluyen reportes (partiendo de datos SQL)\"     \"  \nTenho trabalhado como freelance (B2B) fazendo Shiny Apps, que incluem reportes (partindo de dados SQL)\"
summary2 \"  \nI have experience working with and developing databases (mongo, SQL), scientometrics (https://cyto.shinyapps.io/cerrado/) and programming including the R language, R-shiny, excel VBA, bash, python. I also have experience in downloading databases with scripts (R, python).\" \"  \nTengo experiencia en diseño de bases de datos (mongo, SQL) y aplicaciones shiny, cienciometría (https://cyto.shinyapps.io/cerrado/) y programación incluyendo el lenguaje R, R-shiny, excel VBA, bash, python. Experiencia en acceso o download con scripts (R, VBA, python) a bases de datos. \"  \"  \nNo lado computacional, experiência em bancos de dados and developing databases (mongo, SQL), cientometria (https://cyto.shinyapps.io/cerrado/) e programação, incluindo a linguagem R, R-shiny, excel VBA, bash, python. Experiência em acessar ou baixar por script (R, VBA) bancos de dados. \"
summary3 \"  \nI also applied these and other tools to DNA analysis, such as: Galaxy-based servers, Next Generation Sequencing (RepeatExplorer) reads processing and more specifically, phylogeny and DNA software such as geneious, mafft, iqtree, revBayes.\" \"  \nEstas y otras herramientas las apliqué también a análisis de DNA, como: servidores basados en Galaxy, procesamiento de reads de Next Generation Sequencing (RepeatExplorer) y más específicamente, software de filogenia y ADN como geneious, mafft, iqtree, revBayes.\" \"  \nTambém apliquei essas e outras ferramentas na análise de DNA, como: servidores baseados em Galáxy, sequenciamento de próxima geração (RepeatExplorer)  processamento de reads, mais especificamente, softwares de filogenia e DNA, como Geneious, mafft, iqtree e revBayes.\"
summary4 \"  \nI took the data science course from CorrelationOne, including Jupyter notebooks, SQL and mongo databases, Python libraries to generate data visualizations, perform exploratory data analysis, and analyze data using Pandas. Also included use of different Data Science and AI techniques, such as Decision Trees and the use of kNNs, CNNs, NLP.\" \"  \nTomé el curso de ciencia de datos de CorrelationOne/MinTIC, que incluyó Jupyter notebooks, bases de datos SQL y mongo, uso de bibliotecas Python para generar plots, desarrollar análisis exploratorio de datos, y analizar datos usando Pandas. También incluyó el uso de varias técnicas de Ciencia de Datos y IA, como Decision Trees y el uso de kNNs, CNNs, NLP e interfaces Dash.\" \"  \nParticipei do curso de ciência de dados de CorrelationOne, que incluiu Jupyter notebooks, bases de dados SQL e mongo, uso de bibliotecas Python para gerar plots, desenvolver análises exploratórias de dados, e analisar dados usando Pandas. Também incluiu o uso de várias técnicas de Ciência de Datos e IA, como Decision Trees e o uso de kNNs, CNNs, NLP.\"
summary5 \"  \nI speak English (see TOEFL), Portuguese (lived > 10 y. in Brazil), spanish (Native - Colombia) and some German (german highschool).\" \"  \nHablo inglés, portugués y algo de alemán.\" \"  \nFalo Inglês, Português e um pouco de Alemão.\"
", fill = T, header = T, stringsAsFactors = F
)
attr(summarydata, "dataType") <- "summaryItem"

# summary2 \"  \nI have experience working with and developing databases (mongo, SQL), scientometrics (https://cyto.shinyapps.io/cerrado/) and programming including the R language, R-shiny, excel VBA, bash, python. Experience in accessing or downloading by script (R, VBA)  databases such as gbif, Plants Of the World Online, The Plant List, Open Tree of Life, crossref.\" \"  \nTengo experiencia en diseño de bases de datos (mongo, SQL) y aplicaciones shiny, cienciometría (https://cyto.shinyapps.io/cerrado/) y programación incluyendo el lenguaje R, R-shiny, excel VBA, bash, python. Experiencia en acceso o download con scripts (R, VBA, python) a bases de datos como gbif, Plants Of the World Online, The Plant List, Open Tree of Life, crossref. \"  \"  \nNo lado computacional, experiência em bancos de dados and developing databases (mongo, SQL), cientometria (https://cyto.shinyapps.io/cerrado/) e programação, incluindo a linguagem R, R-shiny, excel VBA, bash, python. Experiência em acessar ou baixar por script (R, VBA) bancos de dados como gbif, Plants Of the World Online, The Plant List, Open Tree of Life, crossref. \"


# summarydata<-data.frame(field="summary1",
#                         english="As researcher I developed several shiny apps and R-packages. I developed and worked with big databases. The cerrado cytogenetics database with a R-shiny frontend with several ggplot graphs and queries; The cytoEvo shiny page also with ggplots of simulated data and the idiogramFISH shiny app, a R-package for plotting chromosomes"
#                         ,spanish="Durante mi experiencia docente en el colegio INEM (2013) implementé varias actividades en páginas wix. Durante mi experiencia como investigador, implementé varias apps shiny (páginas web) que pueden adecuarse a necesidades educacionales en todos los niveles."
#                         ,portuguese=NA
# ,stringsAsFactors=F)
# attr(summarydata, 'dataType') <- "summaryItem"

#
# listofAbstIt<-ls(pattern="summarydata")
# listofAbstItr<-lapply(listofAbstIt, function(x) eval(parse(text=x)) )

# summarydata<-read.table(text="field english spanish portuguese
# summary1 \" \nDuring my scientific carrier, that has taken place mainly in Brazil, I have developed extensive data processing skills focused in problem solutions. Office VBA, R and python are the main languages I use. I have advanced communication skills in english and portuguese ( lived in Brazil 2006-2011; 2014-2020). I am ready to move to any city anytime, i.e. Brazil, Colombia, etc.\" \" \nDurante mi carrera científica, que ha tenido lugar principalmente en Brasil, he desarrollado amplias habilidades de procesamiento de datos (R y python son los principales lenguajes que utilizo). Poseo habilidades comunicativas avanzadas y exámenes de aptitud en inglés y portugués (viví en Brasil 2006-2011; 2014-2020) y también en alemán (pasado).\" \"  \nTenho experiência em genética e citogenética humana (IGH - PUJ) e vegetal, em técnicas como medição do tamanho genômico por citometria, troca de cromátides irmãs, bandas G, FISH. Também tenho experiência com protocolos citogenéticos moleculares, como extração de DNA, tradução de Nick, reações de restrição e PCR. Outras técnicas foram aplicadas em cursos práticos, como extração de RNA e microssatélites.\"
# ", fill=T,header=T, stringsAsFactors=F)
# # summary2 \"\" \"  \nDel lado computacional, experiencia en bases de datos, cienciometría (https://cyto.shinyapps.io/cerrado/) y programación incluyendo el lenguaje R, R-shiny, excel VBA, bash, python. Experiencia en acceso o download por script (R, VBA) a bases de datos como gbif, Plants Of the World Online, The Plant List, Open Tree of Life, crossref. \"  \"  \nNo lado computacional, experiência em bancos de dados, cientometria (https://cyto.shinyapps.io/cerrado/) e programação, incluindo a linguagem R, R-shiny, excel VBA, bash, python. Experiência em acessar ou baixar por script (R, VBA) bancos de dados como gbif, Plants Of the World Online, The Plant List, Open Tree of Life, crossref. \"
# # summary3 \"\" \"  \nEstas y otras herramientas las apliqué también a análisis de DNA, como: servidores basados en Galaxy, procesamiento de reads de Next Generation Sequencing (RepeatExplorer) y más específicamente, software de filogenia y ADN como geneious, mafft, iqtree, revBayes.  \nHablo inglés, portugués y algo de alemán.\" \"  \nTambém apliquei essas e outras ferramentas na análise de DNA, como: servidores baseados em Galáxy, sequenciamento de próxima geração (RepeatExplorer)  processamento de reads, mais especificamente, softwares de filogenia e DNA, como Geneious, mafft, iqtree e revBayes. Falo Inglês, Português e um pouco de Alemão.\"
# #", fill=T,header=T, stringsAsFactors=F)
# attr(summarydata, 'dataType') <- "summaryItem"
